### ISSUE TITLE
Dead page link in Watson Query Docs

### ISSUE THREAD

**Issue by nubbyOne** [ibm-cloud-docs/data-virtualization#5]
At this page https://cloud.ibm.com/docs/data-virtualization?topic=data-virtualization-activity-tracker

the following "IBM Cloud Activity Tracker with LogDNA" page link is dead

Watson Query deployments are integrated with Activity Tracker events in [IBM Cloud Activity Tracker with LogDNA](https://cloud.ibm.com/docs/Log-Analysis-with-LogDNA?topic=Log-Analysis-with-LogDNA-getting-started),

**Comment by patsmith-public** [comment]
The page has been removed and the content is now here: https://cloud.ibm.com/docs/data-virtualization?topic=data-virtualization-admin
