### ISSUE TITLE
Command not working as described. 

### ISSUE THREAD

**Issue by rotimiawani** [ibm-cloud-docs/data-virtualization#6]
Doc Link: https://cloud.ibm.com/docs/data-virtualization?topic=data-virtualization-provisioning

<img width="977" alt="Screen Shot 2022-09-01 at 11 53 35 AM" src="https://user-images.githubusercontent.com/105013261/187991097-e3496738-6e7a-4faa-9e6b-d61296047ddb.png">

This command `ibmcloud resource service-instance-create <service-name>` does not show the status of service instance creation.

**Comment by patsmith-public** [comment]
The content has been revised and now links to https://dataplatform.cloud.ibm.com/docs/content/wsj/getting-started/dv-provision.html?context=cpdaas where there are more detailed commands

**Comment by patsmith-public** [comment]
issue addressed
